### ISSUE TITLE
Broken in 1.31.0?

### ISSUE THREAD

**Issue by alistairholt** [BlairLeduc/touch-bar-display#2] opened 2019-02-07 22:04 UTC
I've gotten into the habit of using this extension all the time but after updating to VSCode 1.31.0 today it's no longer working 😢

**Comment by shpontex** [comment] 2019-02-08 08:44
same here, mac os mojave 10.14.2

**Comment by gaomeng1900** [comment] 2019-02-08 08:45
Seems not working for 1.31.0

**Comment by shpontex** [comment] 2019-02-08 08:50
i tried many other touch bar extensions but no one worked
it seems like a general problem

**Comment by alistairholt** [comment] 2019-02-08 08:52
Seems to be an issue for other extensions too: https://github.com/NascHQ/nasc-vscode-mac-touchbar/issues/25.

**Comment by alistairholt** [comment] 2019-02-08 08:58
Is it due to an extra button being added to the default Touch Bar leaving less space, and therefore hiding, touch-bar-display buttons?

**Comment by shpontex** [comment] 2019-02-08 09:00
yes may be , but i dont know the utility of the new button it does the same thing as the old one

**Comment by alistairholt** [comment] 2019-02-08 09:04
I'd ideally like to drop the default buttons entirely and fully customise the Touch Bar but that doesn't seem to be possible 🤔 .

**Comment by shpontex** [comment] 2019-02-08 09:05
yeh , you can do   "keyboard.touchbar.enabled": false,
but all the buttons will be hidden

**Comment by alistairholt** [comment] 2019-02-08 09:06
Yes, frustrating. I do miss the full control I had when using Atom.

**Comment by shpontex** [comment] 2019-02-08 09:10
i added a new issue on vscode github page as well
will see if they can do something...

**Comment by shpontex** [comment] 2019-02-08 09:56
@alistairholt 
i modified the code and removed two button from the touch bar but i doesn't work, so its not a button space problem i think

**Comment by BlairLeduc** [comment] 2019-02-08 11:19
I took a look last night and came to the same conclusion. Thank you everyone for validating this and opening an issue to vscode.

**Comment by BlairLeduc** [comment] 2019-02-08 11:25
If it is a problem with the amount of space, which buttons should we drop?

**Comment by alistairholt** [comment] 2019-02-08 11:27
My personal experience is that I very rarely touch the search icon – I'm usually accessing this via a keyboard shortcut – `cmd+f` or `cmd+shift+f`. I would guess that the extensions icon isn't used _that_ frequently.

**Comment by bpasero** [comment] 2019-02-08 13:39
See this issue as explanation: https://github.com/electron/electron/issues/16473

**Comment by shpontex** [comment] 2019-02-08 13:45
@BlairLeduc
For me it’s the debug button that I don’t use often

**Comment by alistairholt** [comment] 2019-02-08 13:49
> We pushed a fix on our end by changing the icon sizes. Seems fine now.

https://github.com/electron/electron/issues/16473#issuecomment-457283587

Perhaps this would work here too?

**Comment by bpasero** [comment] 2019-02-09 08:23
I cannot reproduce this btw, however I am using the touchbar simulator (https://sindresorhus.com/touch-bar-simulator/) and the buttons showup just fine. 

The change with Electron 3 that we had to work on was a change in how large icons would appear in the touchbar. They showed up much larger causing the touchbar to drop all the debug items at the end because space got little. It is possible that extensions have to update their icon sizes to account for that.

**Comment by bpasero** [comment] 2019-02-09 08:27
One thing that might help is to disable "Show control strip" from:

![image](https://user-images.githubusercontent.com/900690/52518586-de496780-2c4c-11e9-961d-ae5d7d4bb097.png)

**Comment by BlairLeduc** [comment] 2019-02-10 02:02
Unfortunately, VSCode controls the width of the buttons, or perhaps this comes from Electron.  Whichever, this is completely out of the extensions control.

**Comment by Reyshawn** [comment] 2019-02-10 08:07
Same problem.

**Comment by shpontex** [comment] 2019-02-11 06:31
i tried what @bpasero said and disabled "Show control strip" and all the button showed but as you can see in the image below the buttons display has changed
![tuchbar_5](https://user-images.githubusercontent.com/11470266/52548490-582a4e00-2e11-11e9-8bab-8c84f983d577.png)

i tried to remove the buttons one by one and i end up by having 2 buttons work
![touchbar_2](https://user-images.githubusercontent.com/11470266/52548510-73955900-2e11-11e9-8f45-44ea31e5ba79.png)

so i looked inside the vscode files and the touchbar icons has 60px size, so i changed the icons from 100px top 60px and now i got a better buttons display but with the new button on the left i could only get 4 buttons to show, so i removed the debug button.
![touchbar_after](https://user-images.githubusercontent.com/11470266/52548565-ccfd8800-2e11-11e9-83e2-27b93d4d0992.png)

i made a pull request with this update if it can help

**Comment by bpasero** [comment] 2019-02-11 07:07
Changing the size of the icon is the right fix for this, VSCode did the same 👍

**Comment by BlairLeduc** [comment] 2019-02-11 11:32
@shpontex Thanks! I merged the pull request and I will update the store today.

**Comment by BlairLeduc** [comment] 2019-02-14 18:57
The updated extension is up in the Marketplace.  Could someone let me know if the changes work for them?

**Comment by alistairholt** [comment] 2019-02-14 22:19
@BlairLeduc I'm running 1.2.1 from the marketplace but I'm not seeing the any buttons other than the VSCode defaults. 🤔

**Comment by alistairholt** [comment] 2019-02-14 23:13
@BlairLeduc Looks like I spoke too soon. It's now working! 👍

**Closed** 2019-02-15 00:06 UTC
